module.exports={
  entry:'./src/js/show.js',
  output:{
    path:__dirname+'/dist/js',
    filename:'other.js'
  },
  mode:'development',
  module:{
    rules:[
      {
        test:/\.css$/,
        loader:'style-loader!css-loader'
      }
    ]
  },
  devServer:{
    port:8081,
    contentBase:'src'
  }
}